title:              The Data Charmer
tagline:            Thoughts and notes on software development, databases, and QA
description:        A set of experiments on testing in Go, especially testing binary executables within the `go test` framework.
url:                http://datacharmer.github.io

author:
  name:             Giuseppe Maxia
  url:              https://twitter.com/datacharmer
  email:            YourName@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: jekyll-theme-slate
